### ISSUE TITLE
Inquiry some information about DRAM used in the paper

### ISSUE THREAD

**Issue by yqmQ** [hpides/pmem-nvme-dropin#1]
hi!I recently read your paper `Drop It In Like It’s Hot: An Analysis of Persistent Memory
as a Drop-in Replacement for NVMe SSDs`.That is a Excellent paper in Persistent Memory and I try to reappear the lab describe in the paper.However,I can't find any information about DRAM unlike PM and SSD.Therefore，I want to query the detail information about DRAM. Thank you for your help!

**Comment by MaxiBoether** [comment]
Hi! Thank you very much for the kind words and the interest in our paper.

We ran all experiments on a Fujitsu RX2530 M5 node, with a Intel Xeon Gold 5220S in each socket. In each socket, there are 96 GB of DDR4 DRAM at 2666 MT/s (clocked down from 2933 MT/s to match PMem bus speeds). So in total, we have 192 GB of DRAM, but we run all experiments bound to one NUMA node.

I hope this helps you :-). If you have any further questions, please feel free to ask.

**Comment by yqmQ** [comment]
OK .Thanks for your help.
